
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2  # Use the latest version
    hooks:
      - id: pylint
  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3
